---
# tasks file for roles/Nainterceptor.znc
- name: "Install ZNC packages"
  yum: name=znc state=present
  when: ansible_distribution == 'CentOS'
  notify:
    - Enable ZNC
    - Restart ZNC

- name: visudo NOPASSWD
  lineinfile: dest=/etc/sudoers state=present regexp='^%wheel ALL\=' line='%wheel ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: Ensure user exist
  user: name={{ user }} groups=wheel append=yes comment="Main user" shell=/bin/bash password={{ user_password }}

- name: Ensure user key exist
  authorized_key: user={{ user }} key="{{ lookup('file', pub_key_path) }}"

- name: "Replace znc service"
  copy: src=../files/znc.service dest=/usr/lib/systemd/system/znc.service
  notify:
    - Enable ZNC
    - Restart ZNC
